// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package silence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSilencesHandlerFunc turns a function with the right signature into a get silences handler
type GetSilencesHandlerFunc func(GetSilencesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSilencesHandlerFunc) Handle(params GetSilencesParams) middleware.Responder {
	return fn(params)
}

// GetSilencesHandler interface for that can handle valid get silences params
type GetSilencesHandler interface {
	Handle(GetSilencesParams) middleware.Responder
}

// NewGetSilences creates a new http.Handler for the get silences operation
func NewGetSilences(ctx *middleware.Context, handler GetSilencesHandler) *GetSilences {
	return &GetSilences{Context: ctx, Handler: handler}
}

/*
	GetSilences swagger:route GET /silences silence getSilences

Get a list of silences
*/
type GetSilences struct {
	Context *middleware.Context
	Handler GetSilencesHandler
}

func (o *GetSilences) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSilencesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetSilencesBadRequestBody get silences bad request body
//
// swagger:model GetSilencesBadRequestBody
type GetSilencesBadRequestBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this get silences bad request body
func (o *GetSilencesBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSilencesBadRequestBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesBadRequest"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var getSilencesBadRequestBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSilencesBadRequestBodyTypeStatusPropEnum = append(getSilencesBadRequestBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetSilencesBadRequestBodyStatusError captures enum value "error"
	GetSilencesBadRequestBodyStatusError string = "error"
)

// prop value enum
func (o *GetSilencesBadRequestBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSilencesBadRequestBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSilencesBadRequestBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesBadRequest"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("getSilencesBadRequest"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get silences bad request body based on context it is used
func (o *GetSilencesBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSilencesBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSilencesBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetSilencesBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetSilencesInternalServerErrorBody get silences internal server error body
//
// swagger:model GetSilencesInternalServerErrorBody
type GetSilencesInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this get silences internal server error body
func (o *GetSilencesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSilencesInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var getSilencesInternalServerErrorBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSilencesInternalServerErrorBodyTypeStatusPropEnum = append(getSilencesInternalServerErrorBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetSilencesInternalServerErrorBodyStatusError captures enum value "error"
	GetSilencesInternalServerErrorBodyStatusError string = "error"
)

// prop value enum
func (o *GetSilencesInternalServerErrorBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSilencesInternalServerErrorBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSilencesInternalServerErrorBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesInternalServerError"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("getSilencesInternalServerError"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get silences internal server error body based on context it is used
func (o *GetSilencesInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSilencesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSilencesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetSilencesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
