// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package silence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSilenceHandlerFunc turns a function with the right signature into a get silence handler
type GetSilenceHandlerFunc func(GetSilenceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSilenceHandlerFunc) Handle(params GetSilenceParams) middleware.Responder {
	return fn(params)
}

// GetSilenceHandler interface for that can handle valid get silence params
type GetSilenceHandler interface {
	Handle(GetSilenceParams) middleware.Responder
}

// NewGetSilence creates a new http.Handler for the get silence operation
func NewGetSilence(ctx *middleware.Context, handler GetSilenceHandler) *GetSilence {
	return &GetSilence{Context: ctx, Handler: handler}
}

/*
	GetSilence swagger:route GET /silence/{silenceID} silence getSilence

Get a silence by its ID
*/
type GetSilence struct {
	Context *middleware.Context
	Handler GetSilenceHandler
}

func (o *GetSilence) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSilenceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetSilenceInternalServerErrorBody get silence internal server error body
//
// swagger:model GetSilenceInternalServerErrorBody
type GetSilenceInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this get silence internal server error body
func (o *GetSilenceInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSilenceInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getSilenceInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var getSilenceInternalServerErrorBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSilenceInternalServerErrorBodyTypeStatusPropEnum = append(getSilenceInternalServerErrorBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetSilenceInternalServerErrorBodyStatusError captures enum value "error"
	GetSilenceInternalServerErrorBodyStatusError string = "error"
)

// prop value enum
func (o *GetSilenceInternalServerErrorBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSilenceInternalServerErrorBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSilenceInternalServerErrorBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("getSilenceInternalServerError"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("getSilenceInternalServerError"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get silence internal server error body based on context it is used
func (o *GetSilenceInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSilenceInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSilenceInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetSilenceInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetSilenceNotFoundBody get silence not found body
//
// swagger:model GetSilenceNotFoundBody
type GetSilenceNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this get silence not found body
func (o *GetSilenceNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSilenceNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getSilenceNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var getSilenceNotFoundBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSilenceNotFoundBodyTypeStatusPropEnum = append(getSilenceNotFoundBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetSilenceNotFoundBodyStatusError captures enum value "error"
	GetSilenceNotFoundBodyStatusError string = "error"
)

// prop value enum
func (o *GetSilenceNotFoundBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSilenceNotFoundBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSilenceNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("getSilenceNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("getSilenceNotFound"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get silence not found body based on context it is used
func (o *GetSilenceNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSilenceNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSilenceNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetSilenceNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
