version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
    groups:
      aws:
        patterns:
          - "github.com/aws/*"
          - "github.com/go-openapi/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/ui/mantine-ui"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
