// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cluster.proto

package clusterpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberlistMessage_Kind int32

const (
	MemberlistMessage_STREAM MemberlistMessage_Kind = 0
	MemberlistMessage_PACKET MemberlistMessage_Kind = 1
)

// Enum value maps for MemberlistMessage_Kind.
var (
	MemberlistMessage_Kind_name = map[int32]string{
		0: "STREAM",
		1: "PACKET",
	}
	MemberlistMessage_Kind_value = map[string]int32{
		"STREAM": 0,
		"PACKET": 1,
	}
)

func (x MemberlistMessage_Kind) Enum() *MemberlistMessage_Kind {
	p := new(MemberlistMessage_Kind)
	*p = x
	return p
}

func (x MemberlistMessage_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberlistMessage_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_enumTypes[0].Descriptor()
}

func (MemberlistMessage_Kind) Type() protoreflect.EnumType {
	return &file_cluster_proto_enumTypes[0]
}

func (x MemberlistMessage_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberlistMessage_Kind.Descriptor instead.
func (MemberlistMessage_Kind) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2, 0}
}

type Part struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Part) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FullState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*Part                `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullState) Reset() {
	*x = FullState{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullState) ProtoMessage() {}

func (x *FullState) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullState.ProtoReflect.Descriptor instead.
func (*FullState) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *FullState) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

type MemberlistMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Kind          MemberlistMessage_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=clusterpb.MemberlistMessage_Kind" json:"kind,omitempty"`
	FromAddr      string                 `protobuf:"bytes,3,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	Msg           []byte                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberlistMessage) Reset() {
	*x = MemberlistMessage{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberlistMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberlistMessage) ProtoMessage() {}

func (x *MemberlistMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberlistMessage.ProtoReflect.Descriptor instead.
func (*MemberlistMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *MemberlistMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MemberlistMessage) GetKind() MemberlistMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return MemberlistMessage_STREAM
}

func (x *MemberlistMessage) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *MemberlistMessage) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\tclusterpb\",\n" +
	"\x04Part\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"2\n" +
	"\tFullState\x12%\n" +
	"\x05parts\x18\x01 \x03(\v2\x0f.clusterpb.PartR\x05parts\"\xb3\x01\n" +
	"\x11MemberlistMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x125\n" +
	"\x04kind\x18\x02 \x01(\x0e2!.clusterpb.MemberlistMessage.KindR\x04kind\x12\x1b\n" +
	"\tfrom_addr\x18\x03 \x01(\tR\bfromAddr\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\fR\x03msg\"\x1e\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06STREAM\x10\x00\x12\n" +
	"\n" +
	"\x06PACKET\x10\x01B6Z4github.com/prometheus/alertmanager/cluster/clusterpbb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cluster_proto_goTypes = []any{
	(MemberlistMessage_Kind)(0), // 0: clusterpb.MemberlistMessage.Kind
	(*Part)(nil),                // 1: clusterpb.Part
	(*FullState)(nil),           // 2: clusterpb.FullState
	(*MemberlistMessage)(nil),   // 3: clusterpb.MemberlistMessage
}
var file_cluster_proto_depIdxs = []int32{
	1, // 0: clusterpb.FullState.parts:type_name -> clusterpb.Part
	0, // 1: clusterpb.MemberlistMessage.kind:type_name -> clusterpb.MemberlistMessage.Kind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
