version: "2"
linters:
  default: none
  enable:
    - depguard
    - errorlint
    - godot
    - misspell
    - revive
    - sloglint
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: sync/atomic
              desc: "Use go.uber.org/atomic instead of sync/atomic"
            - pkg: github.com/stretchr/testify/assert
              desc: "Use github.com/stretchr/testify/require instead of github.com/stretchr/testify/assert"
            - pkg: github.com/go-kit/kit/log
              desc: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
            - pkg: github.com/pkg/errors
              desc: "Use errors or fmt instead of github.com/pkg/errors"
    errcheck:
      exclude-functions:
        - io.Copy
        - io.WriteString
        - (net/http.ResponseWriter).Write
        - (*net/http.Server).Shutdown
        - (github.com/prometheus/prometheus/storage.Appender).Rollback
    godot:
      scope: toplevel
      exclude:
        - "^ ?This file is safe to edit"
        - "^ ?scheme value"
      period: true
      capital: true
    revive:
      rules:
        - name: exported
          disabled: true
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    paths:
      - ^.*\.(pb|y)\.go$
    rules:
      - linters:
          - errcheck
        path: _test.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  timeout: 5m
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/prometheus/alertmanager
