// Code generated by idemvfsgen; DO NOT EDIT.

// +build ignore

package main

import (
	"fmt"
	"time"

	"github.com/prometheus/alertmanager/pkg/idemvfs"
)

type identity struct {
	checksum string
	modTime  time.Time
	size     int64
}

func (i identity) Checksum() []byte {
	if len(i.checksum) == 0 {
		return nil
	}
	var b = make([]byte, 0)
	_, err := fmt.Sscanf(i.checksum, "%x", &b)
	if err != nil {
		panic(err)
	}
	return b
}

func (i identity) ModTime() time.Time {
	return i.modTime
}

func (i identity) Size() int64 {
	return i.size
}

type fileIdentifier map[string]identity

func (f fileIdentifier) Identify(name string) (idemvfs.Identity, bool) {
	ident, ok := f[name]
	return ident, ok
}

var identifier = fileIdentifier{
	"/": identity{
		checksum: "",
		modTime:  time.Time{},
		size:     0,
	},
	"/static": identity{
		checksum: "",
		modTime:  time.Date(2018, 8, 28, 17, 36, 45, 181656756, time.UTC),
		size:     0,
	},
	"/static/favicon.ico": identity{
		checksum: "d72fc7b0bd1a4c1c4a016dfa4bfd594b2fb65a409575ec8f857864d4bdc658be",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 121240498, time.UTC),
		size:     15086,
	},
	"/static/index.html": identity{
		checksum: "b92333e982a0c5f11150e68b6cd9e211bc6230ac23170c31d03d2484d44b0c96",
		modTime:  time.Date(2018, 8, 27, 17, 5, 10, 237696286, time.UTC),
		size:     1009,
	},
	"/static/lib": identity{
		checksum: "",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 122240498, time.UTC),
		size:     0,
	},
	"/static/lib/bootstrap-4.0.0-alpha.6-dist": identity{
		checksum: "",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 121240498, time.UTC),
		size:     0,
	},
	"/static/lib/bootstrap-4.0.0-alpha.6-dist/css": identity{
		checksum: "",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 122240498, time.UTC),
		size:     0,
	},
	"/static/lib/bootstrap-4.0.0-alpha.6-dist/css/bootstrap.min.css": identity{
		checksum: "aebf611c1438dc7ec748e9a6364c734066b34bf2a1c7e2fc6511ed784635b50e",
		modTime:  time.Date(2018, 8, 30, 16, 40, 53, 292496262, time.UTC),
		size:     150996,
	},
	"/static/lib/bootstrap-4.0.0-alpha.6-dist/css/bootstrap.min.css.map": identity{
		checksum: "aebcd39a2e455a724a2f4f47dc9834af29719aee121f2d798125280d4b11dc45",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 122240498, time.UTC),
		size:     68044,
	},
	"/static/lib/font-awesome-4.7.0": identity{
		checksum: "",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 122240498, time.UTC),
		size:     0,
	},
	"/static/lib/font-awesome-4.7.0/css": identity{
		checksum: "",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 122240498, time.UTC),
		size:     0,
	},
	"/static/lib/font-awesome-4.7.0/css/font-awesome.css": identity{
		checksum: "36e0a7e08bee65774168528938072c536437669c1b7458ac77976ec788e4439c",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 122240498, time.UTC),
		size:     37414,
	},
	"/static/lib/font-awesome-4.7.0/css/font-awesome.min.css": identity{
		checksum: "799aeb25cc0373fdee0e1b1db7ad6c2f6a0e058dfadaa3379689f583213190bd",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 122240498, time.UTC),
		size:     31000,
	},
	"/static/lib/font-awesome-4.7.0/fonts": identity{
		checksum: "",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 129240495, time.UTC),
		size:     0,
	},
	"/static/lib/font-awesome-4.7.0/fonts/FontAwesome.otf": identity{
		checksum: "444dd4366615ffc4a16d012b2fa90137065d3ccb410fa6fd5e4ddd7b5e4ffcd5",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 124240497, time.UTC),
		size:     134808,
	},
	"/static/lib/font-awesome-4.7.0/fonts/fontawesome-webfont.eot": identity{
		checksum: "7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 125240497, time.UTC),
		size:     165742,
	},
	"/static/lib/font-awesome-4.7.0/fonts/fontawesome-webfont.svg": identity{
		checksum: "ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 127240496, time.UTC),
		size:     444379,
	},
	"/static/lib/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf": identity{
		checksum: "aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 129240495, time.UTC),
		size:     165548,
	},
	"/static/lib/font-awesome-4.7.0/fonts/fontawesome-webfont.woff": identity{
		checksum: "ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 129240495, time.UTC),
		size:     98024,
	},
	"/static/lib/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2": identity{
		checksum: "2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe",
		modTime:  time.Date(2018, 6, 6, 11, 5, 3, 129240495, time.UTC),
		size:     77160,
	},
	"/static/script.js": identity{
		checksum: "6836c36619be75f3a4796cddd38e5c8775258d6306f293a2432405ac350725c5",
		modTime:  time.Date(2018, 8, 30, 16, 41, 6, 815490622, time.UTC),
		size:     191271,
	},
	"/templates": identity{
		checksum: "",
		modTime:  time.Date(2018, 8, 30, 14, 53, 25, 340536803, time.UTC),
		size:     0,
	},
	"/templates/default.tmpl": identity{
		checksum: "4e322bde7c4aaa70d5654bf48c50934e0863aa0363ad2d381b2ae8fe69c2e1b2",
		modTime:  time.Date(2018, 8, 30, 14, 53, 25, 341536802, time.UTC),
		size:     17274,
	},
}
