// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: status/v1/status.proto

package statusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterStatus_State int32

const (
	ClusterStatus_STATE_UNSPECIFIED ClusterStatus_State = 0
	ClusterStatus_STATE_DISABLED    ClusterStatus_State = 1
	ClusterStatus_STATE_SETTLING    ClusterStatus_State = 2
	ClusterStatus_STATE_READY       ClusterStatus_State = 3
)

// Enum value maps for ClusterStatus_State.
var (
	ClusterStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_DISABLED",
		2: "STATE_SETTLING",
		3: "STATE_READY",
	}
	ClusterStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_DISABLED":    1,
		"STATE_SETTLING":    2,
		"STATE_READY":       3,
	}
)

func (x ClusterStatus_State) Enum() *ClusterStatus_State {
	p := new(ClusterStatus_State)
	*p = x
	return p
}

func (x ClusterStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_status_v1_status_proto_enumTypes[0].Descriptor()
}

func (ClusterStatus_State) Type() protoreflect.EnumType {
	return &file_status_v1_status_proto_enumTypes[0]
}

func (x ClusterStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus_State.Descriptor instead.
func (ClusterStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{3, 0}
}

// AlertmanagerStatus is the top-level status payload.
type AlertmanagerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionInfo   *VersionInfo           `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	Config        *AlertmanagerConfig    `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Cluster       *ClusterStatus         `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertmanagerStatus) Reset() {
	*x = AlertmanagerStatus{}
	mi := &file_status_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertmanagerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertmanagerStatus) ProtoMessage() {}

func (x *AlertmanagerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertmanagerStatus.ProtoReflect.Descriptor instead.
func (*AlertmanagerStatus) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *AlertmanagerStatus) GetVersionInfo() *VersionInfo {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

func (x *AlertmanagerStatus) GetConfig() *AlertmanagerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AlertmanagerStatus) GetCluster() *ClusterStatus {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *AlertmanagerStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// VersionInfo describes the running Alertmanager binary.
type VersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	BuildUser     string                 `protobuf:"bytes,4,opt,name=build_user,json=buildUser,proto3" json:"build_user,omitempty"`
	BuildDate     string                 `protobuf:"bytes,5,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	GoVersion     string                 `protobuf:"bytes,6,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_status_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *VersionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionInfo) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *VersionInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *VersionInfo) GetBuildUser() string {
	if x != nil {
		return x.BuildUser
	}
	return ""
}

func (x *VersionInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *VersionInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

// AlertmanagerConfig carries the currently loaded configuration.
type AlertmanagerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original YAML configuration as a single string.
	Original      string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertmanagerConfig) Reset() {
	*x = AlertmanagerConfig{}
	mi := &file_status_v1_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertmanagerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertmanagerConfig) ProtoMessage() {}

func (x *AlertmanagerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertmanagerConfig.ProtoReflect.Descriptor instead.
func (*AlertmanagerConfig) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{2}
}

func (x *AlertmanagerConfig) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

// ClusterStatus describes the local node's view of the gossip cluster.
type ClusterStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cluster name, when configured.
	Name          string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         ClusterStatus_State `protobuf:"varint,2,opt,name=state,proto3,enum=status.v1.ClusterStatus_State" json:"state,omitempty"`
	Peers         []*PeerStatus       `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_status_v1_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterStatus) GetState() ClusterStatus_State {
	if x != nil {
		return x.State
	}
	return ClusterStatus_STATE_UNSPECIFIED
}

func (x *ClusterStatus) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

// PeerStatus is a single peer in the gossip cluster.
type PeerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_status_v1_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{4}
}

func (x *PeerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_status_v1_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{5}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *AlertmanagerStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_status_v1_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetStatus() *AlertmanagerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_status_v1_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{7}
}

type GetHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready is true once the API has received at least one configuration
	// update; before that, requests against business-data services may not
	// reflect the operator's intended configuration.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// healthy is true while the process is able to serve requests. Always
	// true at the application level; intended for completeness and parity
	// with common probe shapes.
	Healthy       bool `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_status_v1_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_v1_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_status_v1_status_proto_rawDescGZIP(), []int{8}
}

func (x *GetHealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GetHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_status_v1_status_proto protoreflect.FileDescriptor

const file_status_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x16status/v1/status.proto\x12\tstatus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n" +
	"\x12AlertmanagerStatus\x129\n" +
	"\fversion_info\x18\x01 \x01(\v2\x16.status.v1.VersionInfoR\vversionInfo\x125\n" +
	"\x06config\x18\x02 \x01(\v2\x1d.status.v1.AlertmanagerConfigR\x06config\x122\n" +
	"\acluster\x18\x03 \x01(\v2\x18.status.v1.ClusterStatusR\acluster\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\xb8\x01\n" +
	"\vVersionInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"build_user\x18\x04 \x01(\tR\tbuildUser\x12\x1d\n" +
	"\n" +
	"build_date\x18\x05 \x01(\tR\tbuildDate\x12\x1d\n" +
	"\n" +
	"go_version\x18\x06 \x01(\tR\tgoVersion\"0\n" +
	"\x12AlertmanagerConfig\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal\"\xdf\x01\n" +
	"\rClusterStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.status.v1.ClusterStatus.StateR\x05state\x12+\n" +
	"\x05peers\x18\x03 \x03(\v2\x15.status.v1.PeerStatusR\x05peers\"W\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATE_DISABLED\x10\x01\x12\x12\n" +
	"\x0eSTATE_SETTLING\x10\x02\x12\x0f\n" +
	"\vSTATE_READY\x10\x03\":\n" +
	"\n" +
	"PeerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x12\n" +
	"\x10GetStatusRequest\"J\n" +
	"\x11GetStatusResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.status.v1.AlertmanagerStatusR\x06status\"\x12\n" +
	"\x10GetHealthRequest\"C\n" +
	"\x11GetHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy2\xa3\x01\n" +
	"\rStatusService\x12H\n" +
	"\tGetStatus\x12\x1b.status.v1.GetStatusRequest\x1a\x1c.status.v1.GetStatusResponse\"\x00\x12H\n" +
	"\tGetHealth\x12\x1b.status.v1.GetHealthRequest\x1a\x1c.status.v1.GetHealthResponse\"\x00B;Z9github.com/prometheus/alertmanager/api/status/v1;statusv1b\x06proto3"

var (
	file_status_v1_status_proto_rawDescOnce sync.Once
	file_status_v1_status_proto_rawDescData []byte
)

func file_status_v1_status_proto_rawDescGZIP() []byte {
	file_status_v1_status_proto_rawDescOnce.Do(func() {
		file_status_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_v1_status_proto_rawDesc), len(file_status_v1_status_proto_rawDesc)))
	})
	return file_status_v1_status_proto_rawDescData
}

var file_status_v1_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_status_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_status_v1_status_proto_goTypes = []any{
	(ClusterStatus_State)(0),      // 0: status.v1.ClusterStatus.State
	(*AlertmanagerStatus)(nil),    // 1: status.v1.AlertmanagerStatus
	(*VersionInfo)(nil),           // 2: status.v1.VersionInfo
	(*AlertmanagerConfig)(nil),    // 3: status.v1.AlertmanagerConfig
	(*ClusterStatus)(nil),         // 4: status.v1.ClusterStatus
	(*PeerStatus)(nil),            // 5: status.v1.PeerStatus
	(*GetStatusRequest)(nil),      // 6: status.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 7: status.v1.GetStatusResponse
	(*GetHealthRequest)(nil),      // 8: status.v1.GetHealthRequest
	(*GetHealthResponse)(nil),     // 9: status.v1.GetHealthResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_status_v1_status_proto_depIdxs = []int32{
	2,  // 0: status.v1.AlertmanagerStatus.version_info:type_name -> status.v1.VersionInfo
	3,  // 1: status.v1.AlertmanagerStatus.config:type_name -> status.v1.AlertmanagerConfig
	4,  // 2: status.v1.AlertmanagerStatus.cluster:type_name -> status.v1.ClusterStatus
	10, // 3: status.v1.AlertmanagerStatus.start_time:type_name -> google.protobuf.Timestamp
	0,  // 4: status.v1.ClusterStatus.state:type_name -> status.v1.ClusterStatus.State
	5,  // 5: status.v1.ClusterStatus.peers:type_name -> status.v1.PeerStatus
	1,  // 6: status.v1.GetStatusResponse.status:type_name -> status.v1.AlertmanagerStatus
	6,  // 7: status.v1.StatusService.GetStatus:input_type -> status.v1.GetStatusRequest
	8,  // 8: status.v1.StatusService.GetHealth:input_type -> status.v1.GetHealthRequest
	7,  // 9: status.v1.StatusService.GetStatus:output_type -> status.v1.GetStatusResponse
	9,  // 10: status.v1.StatusService.GetHealth:output_type -> status.v1.GetHealthResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_status_v1_status_proto_init() }
func file_status_v1_status_proto_init() {
	if File_status_v1_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_v1_status_proto_rawDesc), len(file_status_v1_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_v1_status_proto_goTypes,
		DependencyIndexes: file_status_v1_status_proto_depIdxs,
		EnumInfos:         file_status_v1_status_proto_enumTypes,
		MessageInfos:      file_status_v1_status_proto_msgTypes,
	}.Build()
	File_status_v1_status_proto = out.File
	file_status_v1_status_proto_goTypes = nil
	file_status_v1_status_proto_depIdxs = nil
}
