// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Timestamp
	NotificationInfo
	NotificationInfoSet
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	Seconds     int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanoseconds int32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotificationInfo struct {
	Receiver  string     `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Alert     uint64     `protobuf:"varint,2,opt,name=alert" json:"alert,omitempty"`
	Resolved  bool       `protobuf:"varint,3,opt,name=resolved" json:"resolved,omitempty"`
	Timestamp *Timestamp `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
	ExpiresAt *Timestamp `protobuf:"bytes,5,opt,name=expiresAt" json:"expiresAt,omitempty"`
}

func (m *NotificationInfo) Reset()                    { *m = NotificationInfo{} }
func (m *NotificationInfo) String() string            { return proto.CompactTextString(m) }
func (*NotificationInfo) ProtoMessage()               {}
func (*NotificationInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NotificationInfo) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NotificationInfo) GetExpiresAt() *Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

type NotificationInfoSet struct {
	Infos []*NotificationInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
}

func (m *NotificationInfoSet) Reset()                    { *m = NotificationInfoSet{} }
func (m *NotificationInfoSet) String() string            { return proto.CompactTextString(m) }
func (*NotificationInfoSet) ProtoMessage()               {}
func (*NotificationInfoSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NotificationInfoSet) GetInfos() []*NotificationInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "msg.Timestamp")
	proto.RegisterType((*NotificationInfo)(nil), "msg.NotificationInfo")
	proto.RegisterType((*NotificationInfoSet)(nil), "msg.NotificationInfoSet")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0xb7, 0xd1, 0x66, 0x0a, 0x22, 0x51, 0x21, 0x78, 0x2a, 0x7b, 0x12, 0x94, 0x1e,
	0xf4, 0x09, 0xf4, 0x22, 0x5e, 0x3c, 0x44, 0x5f, 0x20, 0x6e, 0xa7, 0x12, 0xe8, 0x66, 0x96, 0x64,
	0x28, 0x3e, 0x9c, 0x0f, 0x67, 0x36, 0xcb, 0x46, 0x59, 0x7a, 0x9b, 0x7f, 0xfe, 0x6f, 0x7e, 0x66,
	0x06, 0x64, 0x17, 0xbf, 0x36, 0x7d, 0x20, 0x26, 0x55, 0xa7, 0xb2, 0x79, 0x01, 0xf9, 0xe1, 0x3a,
	0x8c, 0x6c, 0xbb, 0x5e, 0x69, 0x38, 0x8b, 0xd8, 0x92, 0xdf, 0x46, 0x5d, 0xad, 0xab, 0xdb, 0xda,
	0x4c, 0x52, 0xad, 0x61, 0xe5, 0xad, 0xa7, 0xc9, 0x3d, 0x49, 0xae, 0x30, 0xff, 0x5b, 0xcd, 0x4f,
	0x05, 0x17, 0x6f, 0xc4, 0x6e, 0xe7, 0x5a, 0xcb, 0x8e, 0xfc, 0xab, 0xdf, 0x91, 0xba, 0x81, 0x65,
	0xc0, 0x16, 0xdd, 0x01, 0x43, 0x4e, 0x94, 0xa6, 0x68, 0x75, 0x05, 0xc2, 0xee, 0x31, 0x70, 0x0e,
	0x5b, 0x98, 0x51, 0x8c, 0x13, 0x91, 0xf6, 0x07, 0xdc, 0xea, 0x3a, 0x19, 0x4b, 0x53, 0xb4, 0xba,
	0x07, 0xc9, 0xd3, 0xae, 0x7a, 0x91, 0xcc, 0xd5, 0xc3, 0xf9, 0x66, 0xb8, 0xa7, 0x5c, 0x60, 0xfe,
	0x80, 0x81, 0xc6, 0xef, 0xde, 0xa5, 0xe9, 0x27, 0xd6, 0xe2, 0x38, 0x5d, 0x80, 0xe6, 0x19, 0x2e,
	0xe7, 0xdb, 0xbf, 0x23, 0xab, 0x3b, 0x10, 0x2e, 0x95, 0xc3, 0x3f, 0xea, 0x14, 0x70, 0x9d, 0x03,
	0xe6, 0xa0, 0x19, 0x99, 0xcf, 0xd3, 0xfc, 0xd7, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf,
	0x6f, 0x04, 0x82, 0x64, 0x01, 0x00, 0x00,
}
