{-
   Alertmanager API
   API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

   OpenAPI spec version: 0.0.1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.AlertmanagerConfig exposing (AlertmanagerConfig, decoder, encoder)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias AlertmanagerConfig =
    { original : String
    }


decoder : Decoder AlertmanagerConfig
decoder =
    Decode.succeed AlertmanagerConfig
        |> required "original" Decode.string


encoder : AlertmanagerConfig -> Encode.Value
encoder model =
    Encode.object
        [ ( "original", Encode.string model.original )
        ]
