{-
   Alertmanager API
   API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

   OpenAPI spec version: 0.0.1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.PostableAlerts exposing (PostableAlerts, decoder, encoder)

import Data.PostableAlert as PostableAlert exposing (PostableAlert)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias PostableAlerts =
    List PostableAlert


decoder : Decoder PostableAlerts
decoder =
    Decode.list PostableAlert.decoder


encoder : PostableAlerts -> Encode.Value
encoder items =
    Encode.list PostableAlert.encoder items
