{-
   Alertmanager API
   API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

   OpenAPI spec version: 0.0.1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Silences exposing (Silences, decoder, encoder)

import Data.Silence as Silence exposing (Silence)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Silences =
    List Silence


decoder : Decoder Silences
decoder =
    Decode.list Silence.decoder


encoder : Silences -> Encode.Value
encoder items =
    Encode.list Silence.encoder items
