{-
   Alertmanager API
   API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

   OpenAPI spec version: 0.0.1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.User exposing (User, decoder, encoder)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias User =
    { username : String
    }


decoder : Decoder User
decoder =
    Decode.succeed User
        |> required "username" Decode.string


encoder : User -> Encode.Value
encoder model =
    Encode.object
        [ ( "username", Encode.string model.username )
        ]
