// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package silence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteSilenceReader is a Reader for the DeleteSilence structure.
type DeleteSilenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSilenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSilenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteSilenceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSilenceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /silence/{silenceID}] deleteSilence", response, response.Code())
	}
}

// NewDeleteSilenceOK creates a DeleteSilenceOK with default headers values
func NewDeleteSilenceOK() *DeleteSilenceOK {
	return &DeleteSilenceOK{}
}

/*
DeleteSilenceOK describes a response with status code 200, with default header values.

Delete silence response
*/
type DeleteSilenceOK struct {
}

// IsSuccess returns true when this delete silence o k response has a 2xx status code
func (o *DeleteSilenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete silence o k response has a 3xx status code
func (o *DeleteSilenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete silence o k response has a 4xx status code
func (o *DeleteSilenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete silence o k response has a 5xx status code
func (o *DeleteSilenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete silence o k response a status code equal to that given
func (o *DeleteSilenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete silence o k response
func (o *DeleteSilenceOK) Code() int {
	return 200
}

func (o *DeleteSilenceOK) Error() string {
	return fmt.Sprintf("[DELETE /silence/{silenceID}][%d] deleteSilenceOK", 200)
}

func (o *DeleteSilenceOK) String() string {
	return fmt.Sprintf("[DELETE /silence/{silenceID}][%d] deleteSilenceOK", 200)
}

func (o *DeleteSilenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSilenceNotFound creates a DeleteSilenceNotFound with default headers values
func NewDeleteSilenceNotFound() *DeleteSilenceNotFound {
	return &DeleteSilenceNotFound{}
}

/*
DeleteSilenceNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type DeleteSilenceNotFound struct {
	Payload *DeleteSilenceNotFoundBody
}

// IsSuccess returns true when this delete silence not found response has a 2xx status code
func (o *DeleteSilenceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete silence not found response has a 3xx status code
func (o *DeleteSilenceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete silence not found response has a 4xx status code
func (o *DeleteSilenceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete silence not found response has a 5xx status code
func (o *DeleteSilenceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete silence not found response a status code equal to that given
func (o *DeleteSilenceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete silence not found response
func (o *DeleteSilenceNotFound) Code() int {
	return 404
}

func (o *DeleteSilenceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /silence/{silenceID}][%d] deleteSilenceNotFound %s", 404, payload)
}

func (o *DeleteSilenceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /silence/{silenceID}][%d] deleteSilenceNotFound %s", 404, payload)
}

func (o *DeleteSilenceNotFound) GetPayload() *DeleteSilenceNotFoundBody {
	return o.Payload
}

func (o *DeleteSilenceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteSilenceNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSilenceInternalServerError creates a DeleteSilenceInternalServerError with default headers values
func NewDeleteSilenceInternalServerError() *DeleteSilenceInternalServerError {
	return &DeleteSilenceInternalServerError{}
}

/*
DeleteSilenceInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteSilenceInternalServerError struct {
	Payload *DeleteSilenceInternalServerErrorBody
}

// IsSuccess returns true when this delete silence internal server error response has a 2xx status code
func (o *DeleteSilenceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete silence internal server error response has a 3xx status code
func (o *DeleteSilenceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete silence internal server error response has a 4xx status code
func (o *DeleteSilenceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete silence internal server error response has a 5xx status code
func (o *DeleteSilenceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete silence internal server error response a status code equal to that given
func (o *DeleteSilenceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete silence internal server error response
func (o *DeleteSilenceInternalServerError) Code() int {
	return 500
}

func (o *DeleteSilenceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /silence/{silenceID}][%d] deleteSilenceInternalServerError %s", 500, payload)
}

func (o *DeleteSilenceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /silence/{silenceID}][%d] deleteSilenceInternalServerError %s", 500, payload)
}

func (o *DeleteSilenceInternalServerError) GetPayload() *DeleteSilenceInternalServerErrorBody {
	return o.Payload
}

func (o *DeleteSilenceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteSilenceInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
DeleteSilenceInternalServerErrorBody delete silence internal server error body
swagger:model DeleteSilenceInternalServerErrorBody
*/
type DeleteSilenceInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this delete silence internal server error body
func (o *DeleteSilenceInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteSilenceInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteSilenceInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var deleteSilenceInternalServerErrorBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteSilenceInternalServerErrorBodyTypeStatusPropEnum = append(deleteSilenceInternalServerErrorBodyTypeStatusPropEnum, v)
	}
}

const (

	// DeleteSilenceInternalServerErrorBodyStatusError captures enum value "error"
	DeleteSilenceInternalServerErrorBodyStatusError string = "error"
)

// prop value enum
func (o *DeleteSilenceInternalServerErrorBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteSilenceInternalServerErrorBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteSilenceInternalServerErrorBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("deleteSilenceInternalServerError"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("deleteSilenceInternalServerError"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete silence internal server error body based on context it is used
func (o *DeleteSilenceInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteSilenceInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteSilenceInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteSilenceInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteSilenceNotFoundBody delete silence not found body
swagger:model DeleteSilenceNotFoundBody
*/
type DeleteSilenceNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this delete silence not found body
func (o *DeleteSilenceNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteSilenceNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteSilenceNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var deleteSilenceNotFoundBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteSilenceNotFoundBodyTypeStatusPropEnum = append(deleteSilenceNotFoundBodyTypeStatusPropEnum, v)
	}
}

const (

	// DeleteSilenceNotFoundBodyStatusError captures enum value "error"
	DeleteSilenceNotFoundBodyStatusError string = "error"
)

// prop value enum
func (o *DeleteSilenceNotFoundBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteSilenceNotFoundBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteSilenceNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("deleteSilenceNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("deleteSilenceNotFound"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete silence not found body based on context it is used
func (o *DeleteSilenceNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteSilenceNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteSilenceNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteSilenceNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
