// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package silence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/prometheus/alertmanager/api/v2/models"
)

// GetSilencesReader is a Reader for the GetSilences structure.
type GetSilencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSilencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSilencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSilencesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSilencesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /silences] getSilences", response, response.Code())
	}
}

// NewGetSilencesOK creates a GetSilencesOK with default headers values
func NewGetSilencesOK() *GetSilencesOK {
	return &GetSilencesOK{}
}

/*
GetSilencesOK describes a response with status code 200, with default header values.

Get silences response
*/
type GetSilencesOK struct {
	Payload models.GettableSilences
}

// IsSuccess returns true when this get silences o k response has a 2xx status code
func (o *GetSilencesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get silences o k response has a 3xx status code
func (o *GetSilencesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get silences o k response has a 4xx status code
func (o *GetSilencesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get silences o k response has a 5xx status code
func (o *GetSilencesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get silences o k response a status code equal to that given
func (o *GetSilencesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get silences o k response
func (o *GetSilencesOK) Code() int {
	return 200
}

func (o *GetSilencesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /silences][%d] getSilencesOK %s", 200, payload)
}

func (o *GetSilencesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /silences][%d] getSilencesOK %s", 200, payload)
}

func (o *GetSilencesOK) GetPayload() models.GettableSilences {
	return o.Payload
}

func (o *GetSilencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSilencesBadRequest creates a GetSilencesBadRequest with default headers values
func NewGetSilencesBadRequest() *GetSilencesBadRequest {
	return &GetSilencesBadRequest{}
}

/*
GetSilencesBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetSilencesBadRequest struct {
	Payload *GetSilencesBadRequestBody
}

// IsSuccess returns true when this get silences bad request response has a 2xx status code
func (o *GetSilencesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get silences bad request response has a 3xx status code
func (o *GetSilencesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get silences bad request response has a 4xx status code
func (o *GetSilencesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get silences bad request response has a 5xx status code
func (o *GetSilencesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get silences bad request response a status code equal to that given
func (o *GetSilencesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get silences bad request response
func (o *GetSilencesBadRequest) Code() int {
	return 400
}

func (o *GetSilencesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /silences][%d] getSilencesBadRequest %s", 400, payload)
}

func (o *GetSilencesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /silences][%d] getSilencesBadRequest %s", 400, payload)
}

func (o *GetSilencesBadRequest) GetPayload() *GetSilencesBadRequestBody {
	return o.Payload
}

func (o *GetSilencesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetSilencesBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSilencesInternalServerError creates a GetSilencesInternalServerError with default headers values
func NewGetSilencesInternalServerError() *GetSilencesInternalServerError {
	return &GetSilencesInternalServerError{}
}

/*
GetSilencesInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetSilencesInternalServerError struct {
	Payload *GetSilencesInternalServerErrorBody
}

// IsSuccess returns true when this get silences internal server error response has a 2xx status code
func (o *GetSilencesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get silences internal server error response has a 3xx status code
func (o *GetSilencesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get silences internal server error response has a 4xx status code
func (o *GetSilencesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get silences internal server error response has a 5xx status code
func (o *GetSilencesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get silences internal server error response a status code equal to that given
func (o *GetSilencesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get silences internal server error response
func (o *GetSilencesInternalServerError) Code() int {
	return 500
}

func (o *GetSilencesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /silences][%d] getSilencesInternalServerError %s", 500, payload)
}

func (o *GetSilencesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /silences][%d] getSilencesInternalServerError %s", 500, payload)
}

func (o *GetSilencesInternalServerError) GetPayload() *GetSilencesInternalServerErrorBody {
	return o.Payload
}

func (o *GetSilencesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetSilencesInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetSilencesBadRequestBody get silences bad request body
swagger:model GetSilencesBadRequestBody
*/
type GetSilencesBadRequestBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this get silences bad request body
func (o *GetSilencesBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSilencesBadRequestBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesBadRequest"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var getSilencesBadRequestBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSilencesBadRequestBodyTypeStatusPropEnum = append(getSilencesBadRequestBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetSilencesBadRequestBodyStatusError captures enum value "error"
	GetSilencesBadRequestBodyStatusError string = "error"
)

// prop value enum
func (o *GetSilencesBadRequestBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSilencesBadRequestBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSilencesBadRequestBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesBadRequest"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("getSilencesBadRequest"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get silences bad request body based on context it is used
func (o *GetSilencesBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSilencesBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSilencesBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetSilencesBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetSilencesInternalServerErrorBody get silences internal server error body
swagger:model GetSilencesInternalServerErrorBody
*/
type GetSilencesInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// error type
	ErrorType string `json:"errorType,omitempty"`

	// status
	// Required: true
	// Enum: ["error"]
	Status *string `json:"status"`
}

// Validate validates this get silences internal server error body
func (o *GetSilencesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSilencesInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

var getSilencesInternalServerErrorBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSilencesInternalServerErrorBodyTypeStatusPropEnum = append(getSilencesInternalServerErrorBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetSilencesInternalServerErrorBodyStatusError captures enum value "error"
	GetSilencesInternalServerErrorBodyStatusError string = "error"
)

// prop value enum
func (o *GetSilencesInternalServerErrorBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSilencesInternalServerErrorBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSilencesInternalServerErrorBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("getSilencesInternalServerError"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("getSilencesInternalServerError"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get silences internal server error body based on context it is used
func (o *GetSilencesInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSilencesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSilencesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetSilencesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
