// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package alertgroupinfolist

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/prometheus/alertmanager/api/v2/models"
)

// GetAlertGroupInfoListReader is a Reader for the GetAlertGroupInfoList structure.
type GetAlertGroupInfoListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAlertGroupInfoListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAlertGroupInfoListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAlertGroupInfoListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAlertGroupInfoListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAlertGroupInfoListOK creates a GetAlertGroupInfoListOK with default headers values
func NewGetAlertGroupInfoListOK() *GetAlertGroupInfoListOK {
	return &GetAlertGroupInfoListOK{}
}

/*
GetAlertGroupInfoListOK describes a response with status code 200, with default header values.

Get alert groups info response
*/
type GetAlertGroupInfoListOK struct {
	Payload *models.AlertGroupInfoList
}

// IsSuccess returns true when this get alert group info list o k response has a 2xx status code
func (o *GetAlertGroupInfoListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get alert group info list o k response has a 3xx status code
func (o *GetAlertGroupInfoListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get alert group info list o k response has a 4xx status code
func (o *GetAlertGroupInfoListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get alert group info list o k response has a 5xx status code
func (o *GetAlertGroupInfoListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get alert group info list o k response a status code equal to that given
func (o *GetAlertGroupInfoListOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAlertGroupInfoListOK) Error() string {
	return fmt.Sprintf("[GET /alertgroups][%d] getAlertGroupInfoListOK  %+v", 200, o.Payload)
}

func (o *GetAlertGroupInfoListOK) String() string {
	return fmt.Sprintf("[GET /alertgroups][%d] getAlertGroupInfoListOK  %+v", 200, o.Payload)
}

func (o *GetAlertGroupInfoListOK) GetPayload() *models.AlertGroupInfoList {
	return o.Payload
}

func (o *GetAlertGroupInfoListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertGroupInfoList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAlertGroupInfoListBadRequest creates a GetAlertGroupInfoListBadRequest with default headers values
func NewGetAlertGroupInfoListBadRequest() *GetAlertGroupInfoListBadRequest {
	return &GetAlertGroupInfoListBadRequest{}
}

/*
GetAlertGroupInfoListBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetAlertGroupInfoListBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get alert group info list bad request response has a 2xx status code
func (o *GetAlertGroupInfoListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get alert group info list bad request response has a 3xx status code
func (o *GetAlertGroupInfoListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get alert group info list bad request response has a 4xx status code
func (o *GetAlertGroupInfoListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get alert group info list bad request response has a 5xx status code
func (o *GetAlertGroupInfoListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get alert group info list bad request response a status code equal to that given
func (o *GetAlertGroupInfoListBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetAlertGroupInfoListBadRequest) Error() string {
	return fmt.Sprintf("[GET /alertgroups][%d] getAlertGroupInfoListBadRequest  %+v", 400, o.Payload)
}

func (o *GetAlertGroupInfoListBadRequest) String() string {
	return fmt.Sprintf("[GET /alertgroups][%d] getAlertGroupInfoListBadRequest  %+v", 400, o.Payload)
}

func (o *GetAlertGroupInfoListBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetAlertGroupInfoListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAlertGroupInfoListInternalServerError creates a GetAlertGroupInfoListInternalServerError with default headers values
func NewGetAlertGroupInfoListInternalServerError() *GetAlertGroupInfoListInternalServerError {
	return &GetAlertGroupInfoListInternalServerError{}
}

/*
GetAlertGroupInfoListInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAlertGroupInfoListInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get alert group info list internal server error response has a 2xx status code
func (o *GetAlertGroupInfoListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get alert group info list internal server error response has a 3xx status code
func (o *GetAlertGroupInfoListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get alert group info list internal server error response has a 4xx status code
func (o *GetAlertGroupInfoListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get alert group info list internal server error response has a 5xx status code
func (o *GetAlertGroupInfoListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get alert group info list internal server error response a status code equal to that given
func (o *GetAlertGroupInfoListInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetAlertGroupInfoListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /alertgroups][%d] getAlertGroupInfoListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAlertGroupInfoListInternalServerError) String() string {
	return fmt.Sprintf("[GET /alertgroups][%d] getAlertGroupInfoListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAlertGroupInfoListInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetAlertGroupInfoListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
