// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: alertmanager/v3/status.proto

package alertmanagerv3connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	alertmanagerv3 "github.com/prometheus/alertmanager/api/alertmanagerv3"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StatusServiceName is the fully-qualified name of the StatusService service.
	StatusServiceName = "alertmanager.v3.StatusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StatusServiceGetStatusProcedure is the fully-qualified name of the StatusService's GetStatus RPC.
	StatusServiceGetStatusProcedure = "/alertmanager.v3.StatusService/GetStatus"
	// StatusServiceGetHealthProcedure is the fully-qualified name of the StatusService's GetHealth RPC.
	StatusServiceGetHealthProcedure = "/alertmanager.v3.StatusService/GetHealth"
)

// StatusServiceClient is a client for the alertmanager.v3.StatusService service.
type StatusServiceClient interface {
	// GetStatus returns the Alertmanager instance and cluster status.
	GetStatus(context.Context, *connect.Request[alertmanagerv3.GetStatusRequest]) (*connect.Response[alertmanagerv3.GetStatusResponse], error)
	// GetHealth is a lightweight liveness/readiness probe intended for load
	// balancers. It does not acquire any internal locks.
	GetHealth(context.Context, *connect.Request[alertmanagerv3.GetHealthRequest]) (*connect.Response[alertmanagerv3.GetHealthResponse], error)
}

// NewStatusServiceClient constructs a client for the alertmanager.v3.StatusService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStatusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StatusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	statusServiceMethods := alertmanagerv3.File_alertmanager_v3_status_proto.Services().ByName("StatusService").Methods()
	return &statusServiceClient{
		getStatus: connect.NewClient[alertmanagerv3.GetStatusRequest, alertmanagerv3.GetStatusResponse](
			httpClient,
			baseURL+StatusServiceGetStatusProcedure,
			connect.WithSchema(statusServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		getHealth: connect.NewClient[alertmanagerv3.GetHealthRequest, alertmanagerv3.GetHealthResponse](
			httpClient,
			baseURL+StatusServiceGetHealthProcedure,
			connect.WithSchema(statusServiceMethods.ByName("GetHealth")),
			connect.WithClientOptions(opts...),
		),
	}
}

// statusServiceClient implements StatusServiceClient.
type statusServiceClient struct {
	getStatus *connect.Client[alertmanagerv3.GetStatusRequest, alertmanagerv3.GetStatusResponse]
	getHealth *connect.Client[alertmanagerv3.GetHealthRequest, alertmanagerv3.GetHealthResponse]
}

// GetStatus calls alertmanager.v3.StatusService.GetStatus.
func (c *statusServiceClient) GetStatus(ctx context.Context, req *connect.Request[alertmanagerv3.GetStatusRequest]) (*connect.Response[alertmanagerv3.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// GetHealth calls alertmanager.v3.StatusService.GetHealth.
func (c *statusServiceClient) GetHealth(ctx context.Context, req *connect.Request[alertmanagerv3.GetHealthRequest]) (*connect.Response[alertmanagerv3.GetHealthResponse], error) {
	return c.getHealth.CallUnary(ctx, req)
}

// StatusServiceHandler is an implementation of the alertmanager.v3.StatusService service.
type StatusServiceHandler interface {
	// GetStatus returns the Alertmanager instance and cluster status.
	GetStatus(context.Context, *connect.Request[alertmanagerv3.GetStatusRequest]) (*connect.Response[alertmanagerv3.GetStatusResponse], error)
	// GetHealth is a lightweight liveness/readiness probe intended for load
	// balancers. It does not acquire any internal locks.
	GetHealth(context.Context, *connect.Request[alertmanagerv3.GetHealthRequest]) (*connect.Response[alertmanagerv3.GetHealthResponse], error)
}

// NewStatusServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStatusServiceHandler(svc StatusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	statusServiceMethods := alertmanagerv3.File_alertmanager_v3_status_proto.Services().ByName("StatusService").Methods()
	statusServiceGetStatusHandler := connect.NewUnaryHandler(
		StatusServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(statusServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	statusServiceGetHealthHandler := connect.NewUnaryHandler(
		StatusServiceGetHealthProcedure,
		svc.GetHealth,
		connect.WithSchema(statusServiceMethods.ByName("GetHealth")),
		connect.WithHandlerOptions(opts...),
	)
	return "/alertmanager.v3.StatusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StatusServiceGetStatusProcedure:
			statusServiceGetStatusHandler.ServeHTTP(w, r)
		case StatusServiceGetHealthProcedure:
			statusServiceGetHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStatusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStatusServiceHandler struct{}

func (UnimplementedStatusServiceHandler) GetStatus(context.Context, *connect.Request[alertmanagerv3.GetStatusRequest]) (*connect.Response[alertmanagerv3.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("alertmanager.v3.StatusService.GetStatus is not implemented"))
}

func (UnimplementedStatusServiceHandler) GetHealth(context.Context, *connect.Request[alertmanagerv3.GetHealthRequest]) (*connect.Response[alertmanagerv3.GetHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("alertmanager.v3.StatusService.GetHealth is not implemented"))
}
