// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAlertsHandlerFunc turns a function with the right signature into a get alerts handler
type GetAlertsHandlerFunc func(GetAlertsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAlertsHandlerFunc) Handle(params GetAlertsParams) middleware.Responder {
	return fn(params)
}

// GetAlertsHandler interface for that can handle valid get alerts params
type GetAlertsHandler interface {
	Handle(GetAlertsParams) middleware.Responder
}

// NewGetAlerts creates a new http.Handler for the get alerts operation
func NewGetAlerts(ctx *middleware.Context, handler GetAlertsHandler) *GetAlerts {
	return &GetAlerts{Context: ctx, Handler: handler}
}

/*
	GetAlerts swagger:route GET /alerts alert getAlerts

Get a list of alerts
*/
type GetAlerts struct {
	Context *middleware.Context
	Handler GetAlertsHandler
}

func (o *GetAlerts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAlertsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAlertsBadRequestBody get alerts bad request body
//
// swagger:model GetAlertsBadRequestBody
type GetAlertsBadRequestBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this get alerts bad request body
func (o *GetAlertsBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAlertsBadRequestBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getAlertsBadRequest"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get alerts bad request body based on context it is used
func (o *GetAlertsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAlertsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAlertsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetAlertsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetAlertsInternalServerErrorBody get alerts internal server error body
//
// swagger:model GetAlertsInternalServerErrorBody
type GetAlertsInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this get alerts internal server error body
func (o *GetAlertsInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAlertsInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getAlertsInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get alerts internal server error body based on context it is used
func (o *GetAlertsInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAlertsInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAlertsInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetAlertsInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
