// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/prometheus/alertmanager/api/v2/models"
)

// NewPostAlertsParams creates a new PostAlertsParams object
// no default values defined in spec.
func NewPostAlertsParams() PostAlertsParams {

	return PostAlertsParams{}
}

// PostAlertsParams contains all the bound params for the post alerts operation
// typically these are obtained from a http.Request
//
// swagger:parameters postAlerts
type PostAlertsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The alerts to create
	  Required: true
	  In: body
	*/
	Alerts models.PostableAlerts
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAlertsParams() beforehand.
func (o *PostAlertsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PostableAlerts
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("alerts", "body"))
			} else {
				res = append(res, errors.NewParseError("alerts", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Alerts = body
			}
		}
	} else {
		res = append(res, errors.Required("alerts", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
