// Code generated by go-swagger; DO NOT EDIT.

package stored_alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/strfmt"
)

// GetSeverityChartURL generates an URL for the get severity chart operation
type GetSeverityChartURL struct {
	TimeEnd   strfmt.DateTime
	TimeStart strfmt.DateTime

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetSeverityChartURL) WithBasePath(bp string) *GetSeverityChartURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetSeverityChartURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetSeverityChartURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/stored_alerts/severity_days"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v2/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	timeEndQ := o.TimeEnd.String()
	if timeEndQ != "" {
		qs.Set("timeEnd", timeEndQ)
	}

	timeStartQ := o.TimeStart.String()
	if timeStartQ != "" {
		qs.Set("timeStart", timeStartQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetSeverityChartURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetSeverityChartURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetSeverityChartURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetSeverityChartURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetSeverityChartURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetSeverityChartURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
