// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package apipb is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ResponseHeader
	AlertsGetRequest
	AlertsAddRequest
	AlertsGetResponse
	AlertsAddResponse
	Alert
*/
package apipb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ResponseHeader is part of every API response.
type ResponseHeader struct {
	PeerName string `protobuf:"bytes,1,opt,name=peer_name,json=peerName" json:"peer_name,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResponseHeader) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

type AlertsGetRequest struct {
}

func (m *AlertsGetRequest) Reset()                    { *m = AlertsGetRequest{} }
func (m *AlertsGetRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertsGetRequest) ProtoMessage()               {}
func (*AlertsGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AlertsAddRequest struct {
	Alerts []*Alert `protobuf:"bytes,1,rep,name=alerts" json:"alerts,omitempty"`
}

func (m *AlertsAddRequest) Reset()                    { *m = AlertsAddRequest{} }
func (m *AlertsAddRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertsAddRequest) ProtoMessage()               {}
func (*AlertsAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AlertsAddRequest) GetAlerts() []*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type AlertsGetResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Alerts []*Alert        `protobuf:"bytes,2,rep,name=alerts" json:"alerts,omitempty"`
}

func (m *AlertsGetResponse) Reset()                    { *m = AlertsGetResponse{} }
func (m *AlertsGetResponse) String() string            { return proto.CompactTextString(m) }
func (*AlertsGetResponse) ProtoMessage()               {}
func (*AlertsGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AlertsGetResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AlertsGetResponse) GetAlerts() []*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type AlertsAddResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *AlertsAddResponse) Reset()                    { *m = AlertsAddResponse{} }
func (m *AlertsAddResponse) String() string            { return proto.CompactTextString(m) }
func (*AlertsAddResponse) ProtoMessage()               {}
func (*AlertsAddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AlertsAddResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type Alert struct {
	Labels       map[string]string          `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations  map[string]string          `protobuf:"bytes,2,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartsAt     *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=starts_at,json=startsAt" json:"starts_at,omitempty"`
	EndsAt       *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=ends_at,json=endsAt" json:"ends_at,omitempty"`
	GeneratorUrl string                     `protobuf:"bytes,5,opt,name=generator_url,json=generatorUrl" json:"generator_url,omitempty"`
}

func (m *Alert) Reset()                    { *m = Alert{} }
func (m *Alert) String() string            { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()               {}
func (*Alert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Alert) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Alert) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Alert) GetStartsAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartsAt
	}
	return nil
}

func (m *Alert) GetEndsAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndsAt
	}
	return nil
}

func (m *Alert) GetGeneratorUrl() string {
	if m != nil {
		return m.GeneratorUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*ResponseHeader)(nil), "apipb.ResponseHeader")
	proto.RegisterType((*AlertsGetRequest)(nil), "apipb.AlertsGetRequest")
	proto.RegisterType((*AlertsAddRequest)(nil), "apipb.AlertsAddRequest")
	proto.RegisterType((*AlertsGetResponse)(nil), "apipb.AlertsGetResponse")
	proto.RegisterType((*AlertsAddResponse)(nil), "apipb.AlertsAddResponse")
	proto.RegisterType((*Alert)(nil), "apipb.Alert")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Alerts service

type AlertsClient interface {
	Get(ctx context.Context, in *AlertsGetRequest, opts ...grpc.CallOption) (*AlertsGetResponse, error)
	Add(ctx context.Context, in *AlertsAddRequest, opts ...grpc.CallOption) (*AlertsAddResponse, error)
}

type alertsClient struct {
	cc *grpc.ClientConn
}

func NewAlertsClient(cc *grpc.ClientConn) AlertsClient {
	return &alertsClient{cc}
}

func (c *alertsClient) Get(ctx context.Context, in *AlertsGetRequest, opts ...grpc.CallOption) (*AlertsGetResponse, error) {
	out := new(AlertsGetResponse)
	err := grpc.Invoke(ctx, "/apipb.Alerts/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) Add(ctx context.Context, in *AlertsAddRequest, opts ...grpc.CallOption) (*AlertsAddResponse, error) {
	out := new(AlertsAddResponse)
	err := grpc.Invoke(ctx, "/apipb.Alerts/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Alerts service

type AlertsServer interface {
	Get(context.Context, *AlertsGetRequest) (*AlertsGetResponse, error)
	Add(context.Context, *AlertsAddRequest) (*AlertsAddResponse, error)
}

func RegisterAlertsServer(s *grpc.Server, srv AlertsServer) {
	s.RegisterService(&_Alerts_serviceDesc, srv)
}

func _Alerts_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apipb.Alerts/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).Get(ctx, req.(*AlertsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertsAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apipb.Alerts/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).Add(ctx, req.(*AlertsAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alerts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apipb.Alerts",
	HandlerType: (*AlertsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Alerts_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Alerts_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x63, 0xe2, 0xd6, 0x93, 0x02, 0x61, 0x05, 0xc2, 0x32, 0x20, 0x2a, 0xc3, 0xa1, 0x97,
	0x3a, 0x28, 0x3d, 0x50, 0x38, 0x80, 0x8c, 0x84, 0x0a, 0x12, 0xe2, 0x60, 0xc1, 0x39, 0x9a, 0xc8,
	0x43, 0x6a, 0xe1, 0xd8, 0xcb, 0xee, 0x18, 0xa9, 0x57, 0x4e, 0xdc, 0xb9, 0xf3, 0x53, 0xfc, 0x02,
	0x1f, 0x82, 0xb2, 0xbb, 0x6e, 0xb7, 0x41, 0x02, 0xc1, 0xcd, 0x7e, 0xf3, 0xde, 0x9b, 0xb7, 0x33,
	0x03, 0x31, 0xca, 0x3a, 0x97, 0xaa, 0xe3, 0x4e, 0x8c, 0x51, 0xd6, 0x72, 0x99, 0xde, 0x5f, 0x75,
	0xdd, 0xaa, 0xa1, 0x99, 0x01, 0x97, 0xfd, 0x87, 0x19, 0xd7, 0x6b, 0xd2, 0x8c, 0x6b, 0x69, 0x79,
	0xe9, 0x5d, 0x47, 0x40, 0x59, 0xcf, 0xb0, 0x6d, 0x3b, 0x46, 0xae, 0xbb, 0x56, 0xdb, 0x6a, 0x76,
	0x08, 0xd7, 0x4a, 0xd2, 0xb2, 0x6b, 0x35, 0xbd, 0x22, 0xac, 0x48, 0x89, 0x3b, 0x10, 0x4b, 0x22,
	0xb5, 0x68, 0x71, 0x4d, 0x49, 0xb0, 0x1f, 0x1c, 0xc4, 0xe5, 0xee, 0x06, 0x78, 0x8b, 0x6b, 0xca,
	0x04, 0x4c, 0x8b, 0x86, 0x14, 0xeb, 0x13, 0xe2, 0x92, 0x3e, 0xf5, 0xa4, 0x39, 0x3b, 0x1e, 0xb0,
	0xa2, 0xaa, 0x1c, 0x26, 0x1e, 0x42, 0x84, 0x06, 0x4b, 0x82, 0xfd, 0xf0, 0x60, 0x32, 0xdf, 0xcb,
	0x4d, 0xda, 0xdc, 0x10, 0x4b, 0x57, 0xcb, 0x4e, 0xe1, 0x86, 0xe7, 0x66, 0x53, 0x88, 0x43, 0x88,
	0x4e, 0x4d, 0x12, 0xd3, 0x7c, 0x32, 0xbf, 0xe5, 0xa4, 0x97, 0x63, 0x96, 0x8e, 0xe4, 0x75, 0x1a,
	0xfd, 0xa1, 0xd3, 0x8b, 0xa1, 0x93, 0xc9, 0xf8, 0x5f, 0x9d, 0xb2, 0xaf, 0x21, 0x8c, 0x8d, 0x89,
	0x78, 0x04, 0x51, 0x83, 0x4b, 0x6a, 0x86, 0xd7, 0x25, 0x7e, 0xcf, 0xfc, 0x8d, 0x29, 0xbd, 0x6c,
	0x59, 0x9d, 0x95, 0x8e, 0x27, 0x9e, 0xc3, 0xc4, 0x9b, 0xbd, 0x8b, 0x7a, 0xef, 0x92, 0xac, 0xb8,
	0xa8, 0x5b, 0xad, 0xaf, 0x10, 0x8f, 0x21, 0xd6, 0x8c, 0x8a, 0xf5, 0x02, 0x39, 0x09, 0x4d, 0xdc,
	0x34, 0xb7, 0x9b, 0xcd, 0x87, 0xd5, 0xe7, 0xef, 0x86, 0xd5, 0x97, 0xbb, 0x96, 0x5c, 0xb0, 0x38,
	0x82, 0x1d, 0x6a, 0x2b, 0x23, 0xbb, 0xf2, 0x57, 0x59, 0xb4, 0xa1, 0x16, 0x2c, 0x1e, 0xc0, 0xd5,
	0x15, 0xb5, 0xa4, 0x90, 0x3b, 0xb5, 0xe8, 0x55, 0x93, 0x8c, 0xcd, 0x1d, 0xec, 0x9d, 0x83, 0xef,
	0x55, 0x93, 0x3e, 0x81, 0x89, 0xf7, 0x54, 0x31, 0x85, 0xf0, 0x23, 0x9d, 0xb9, 0x8b, 0xd9, 0x7c,
	0x8a, 0x9b, 0x30, 0xfe, 0x8c, 0x4d, 0x4f, 0xc9, 0xc8, 0x60, 0xf6, 0xe7, 0xe9, 0xe8, 0x38, 0x48,
	0x9f, 0xc1, 0x74, 0xfb, 0xb9, 0xff, 0xa2, 0x9f, 0x7f, 0x0f, 0x20, 0xb2, 0xfb, 0x14, 0xaf, 0x21,
	0x3c, 0x21, 0x16, 0xb7, 0xfd, 0x59, 0x7a, 0xd7, 0x99, 0x26, 0xbf, 0x17, 0xec, 0x76, 0xb3, 0xeb,
	0x5f, 0x7e, 0xfc, 0xfc, 0x36, 0x8a, 0xc5, 0xce, 0x0c, 0xcf, 0xad, 0x8a, 0xaa, 0xda, 0xb2, 0xba,
	0x38, 0xea, 0x2d, 0x2b, 0xef, 0x92, 0x06, 0xab, 0x6c, 0xb0, 0x5a, 0x46, 0x66, 0xb8, 0x47, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xea, 0x50, 0x36, 0x31, 0xb0, 0x03, 0x00, 0x00,
}
