// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Alertmanager API
API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
