---
name: Publish
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
jobs:
  ci:
    name: Run ci
    uses: ./.github/workflows/ci.yml

  build:
    name: Build Alertmanager for all architectures
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    needs: ci
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: prometheus/promci@443c7fc2397e946bc9f5029e313a9c3441b9b86d # v0.4.7
      - uses: ./.github/promci/actions/build
        with:
          parallelism: 12
          thread: ${{ matrix.thread }}
  publish_main:
    name: Publish main branch artefacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: prometheus/promci@443c7fc2397e946bc9f5029e313a9c3441b9b86d # v0.4.7
      - uses: ./.github/promci/actions/publish_main
        with:
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}
