---
name: Publish
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
jobs:
  ci:
    name: Run ci
    uses: ./.github/workflows/ci.yml

  build:
    name: Build Alertmanager for all architectures
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    needs: ci
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: prometheus/promci@c3c93a50d581b928af720f0134b2b2dad32a6c41 # v0.4.6
      - uses: ./.github/promci/actions/build
        with:
          parallelism: 12
          thread: ${{ matrix.thread }}
  publish_main:
    name: Publish main branch artefacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: prometheus/promci@c3c93a50d581b928af720f0134b2b2dad32a6c41 # v0.4.6
      - uses: ./.github/promci/actions/publish_main
        with:
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}
