name: UI CI

on:
  pull_request:
    branches:
      - '**'
    paths:
      - '.nvmrc'
      - 'ui/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_mantine_ui:
    name: Test mantine-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui/mantine-ui
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: './.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            .nvmrc
            **/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test
