name: UI CI

on:
  pull_request:
    branches:
      - '**'
    paths:
      - '.nvmrc'
      - 'ui/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test_mantine_ui:
    name: Test mantine-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui/mantine-ui
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: './.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            .nvmrc
            **/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test
